apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-bundle-overridingnbfz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-bundle-overridingnbfz
    app.kubernetes.io/part-of: test-app-ghnk
  name: build-suite-test-bundle-overridingnbfz
  namespace: build-e2e-gkld-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-bundle-overridingnbfz
status:
  loadBalancer: {}
